openapi: "3.0.0"
info:
  version: 1.0.0
  title: Example API
  description: <%= 1 + 1 %>
servers:
  - url: http://example.com/v1
paths:
  $ref: ./paths/index.yml
components:
  $ref: ./components/index.yml
